const KEY='ghTranslatorSettings';const DEFAULT={enabled:true,targetLang:'zh-CN',sourceLang:'auto',viewMode:'translated',providerOrder:['argos','google','mymemory','libre']};const cache=new Map();const SKIP='script,style,svg,textarea,input,select,code,pre,noscript,.gh-translation';
const settings=()=>new Promise(r=>chrome.storage.local.get(KEY,x=>r({...DEFAULT,...(x[KEY]||{})})));
const norm=x=>String(x||'').replace(/\s+/g,' ').trim();
function nodes(root){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{if(!n.textContent?.trim()||n.parentElement?.closest(SKIP))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT;}});const out=[];let group=[],parent=null,n;while(n=w.nextNode()){if(!group.length){group=[n];parent=n.parentElement;continue}if(n.parentElement===parent)group.push(n);else{out.push(group);group=[n];parent=n.parentElement}}if(group.length)out.push(group);return out}
async function provider(p,q,s,t){const k=`${p}:${s}:${t}:${q}`;if(cache.has(k))return cache.get(k);try{let d,r;if(p==='google'){const u=new URL('https://translate.googleapis.com/translate_a/single');Object.entries({client:'gtx',sl:s,tl:t,dt:'t',q}).forEach(([a,b])=>u.searchParams.set(a,b));r=await fetch(u);d=await r.json();d=d?.[0]?.map(x=>x[0]).join('')}else if(p==='mymemory'){r=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(q)}&langpair=${encodeURIComponent(s)}|${encodeURIComponent(t)}`);d=(await r.json())?.responseData?.translatedText}else{r=await fetch(p==='argos'?'https://translate.argosopentech.com/translate':'https://libretranslate.com/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q,source:s,target:t,format:'text'})});d=(await r.json())?.translatedText}if(!r.ok||!d?.trim())return'';cache.set(k,d);return d}catch(e){console.warn('[GitHub Auto Translator]',p,e);return''}}
async function translate(q,s,t,order){for(const p of order){const d=await provider(p,q,s,t);if(d)return d}return q}
function replace(group,text){const first=group[0],p=first.parentNode;if(!p)return;const original=norm(group.map(n=>n.textContent).join(' ')),w=document.createElement('span');w.className='gh-translation';const o=document.createElement('span');o.className='gh-translation-original';o.textContent=original;const t=document.createElement('span');t.className='gh-translation-text';t.textContent=text;w.append(o,t);p.insertBefore(w,first);group.forEach(n=>n.remove())}
function mode(m){document.body.dataset.ghTranslationMode=m}
function button(){if(document.getElementById('gh-translation-toggle'))return;const b=document.createElement('button');b.id='gh-translation-toggle';b.textContent='译文';b.onclick=async()=>{const x=await settings(),m=x.viewMode==='translated'?'original':'translated';x.viewMode=m;chrome.storage.local.set({[KEY]:x});mode(m);b.textContent=m==='translated'?'译文':'原文'};document.body.append(b)}
async function translatePage(){const x=await settings();if(!x.enabled)return;for(const g of nodes(document.body)){const q=norm(g.map(n=>n.textContent).join(' '));if(q.length<2)continue;const d=await translate(q,x.sourceLang,x.targetLang,x.providerOrder);if(d&&d!==q)replace(g,d)}mode(x.viewMode)}
async function init(){if(!location.hostname.endsWith('github.com'))return;button();const x=await settings();mode(x.viewMode);if(x.enabled)translatePage();chrome.storage.onChanged.addListener(c=>{if(c[KEY]){mode(c[KEY].newValue.viewMode);if(c[KEY].newValue.enabled)translatePage()}});new MutationObserver(()=>settings().then(x=>x.enabled&&translatePage())).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
